### ISSUE TITLE
Klustaviewa error on loading example file

### ISSUE THREAD

**Issue by grg2rsr** [klusta-team/klustaviewa#53]
I ran the example file from [the example data repository](https://drive.google.com/folderview?id=0BwTrbfNJNihcaHZjTXEwdk44cFE&usp=sharing) that is linked on the readme of klusta-team/example. After getting it only to run with a [different parameter file](https://github.com/klusta-team/example/blob/master/params.prm) (not the one that is in the .zip), I can't open the resulting .kwik file in klustaviewa.

Running linux mint 17.
```
georg@Georg-Desktop ~/programs/klustakwik/example_data $klustaviewa 
2015-05-27 18:17:48  kwikloader:134          Opening test_hybrid_120sec.kwik.

(python:4351): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed

(python:4351): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
2015-05-27 18:17:55  kwikloader:134          Opening test_hybrid_120sec.kwik.
2015-05-27 18:17:55  logger:175              Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/gui/mainwindow.py", line 887, in open_done
    self.taskgraph.update_cluster_view()
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/gui/taskgraph.py", line 75, in <lambda>
    return lambda *args, **kwargs: self.run(('_' + name, args, kwargs))
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/gui/taskgraph.py", line 63, in run
    outputs = self.run_single(action)
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/gui/taskgraph.py", line 52, in run_single
    return getattr(self, method)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/gui/taskgraph.py", line 387, in _update_cluster_view
    self.get_view('ClusterView').set_data(**data)
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/views/clusterview.py", line 554, in set_data
    self.model = ClusterViewModel(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/views/clusterview.py", line 106, in __init__
    self.load(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/views/clusterview.py", line 146, in load
    parent=self.get_group(select(cluster_groups, clusteridx)))
  File "/usr/local/lib/python2.7/dist-packages/klustaviewa-0.3.0-py2.7-linux-x86_64.egg/klustaviewa/views/clusterview.py", line 455, in get_group
    (group.groupidx() == groupidx)][0]
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.16.0-py2.7-linux-x86_64.egg/pandas/core/generic.py", line 709, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
None
<klustaviewa.gui.mainwindow.MainWindow object at 0x7f8f0f223510>
```

**Comment by lepmik** [comment]
Hi, I had the same problem, turned out to be due to python dependiencies - pandas=0.12 and pytables=3.0.0. However, it does not run clean even though it works - i'll make a new issue on this.

**Comment by grg2rsr** [comment]
I have 
> Name: pandas
Version: 0.16.0

and I installed it via the standard ubuntu repositories. So if pandas broke downward compatibility somewhere between `0.12` and `0.16`, a lot of people should suffer from this, or not?

**Comment by rossant** [comment]
yes pandas 0.12 is required (see https://github.com/klusta-team/example/blob/master/install.md#dependencies)

the new version of klustaviewa ([phy](http://phy.cortexlab.net)) does not depend on pandas anymore
