### ISSUE TITLE
IndexError has no attribute 'keys'

### ISSUE THREAD

**Issue by nippoo** [klusta-team/klustaviewa#59]
Traceback:

```
Traceback (most recent call last):
File "C:\Program Files\KlustaViewa\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\klustaviewa\gui\taskgraph.py", line 147, in correlograms_computed_callback
self.correlograms_computed(clusters, correlograms, ncorrbins, corrbin, wizard)
File "C:\Program Files\KlustaViewa\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\klustaviewa\gui\taskgraph.py", line 75, in <lambda>
return lambda *args, **kwargs: self.run(('_' + name, args, kwargs))
File "C:\Program Files\KlustaViewa\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\klustaviewa\gui\taskgraph.py", line 63, in run
outputs = self.run_single(action)
File "C:\Program Files\KlustaViewa\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\klustaviewa\gui\taskgraph.py", line 52, in run_single
return getattr(self, method)(*args, **kwargs)
File "C:\Program Files\KlustaViewa\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\klustaviewa\gui\taskgraph.py", line 269, in _correlograms_computed
self.statscache.correlograms.update(clusters, correlograms)
File "C:\Program Files\KlustaViewa\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\klustaviewa\stats\indexed_matrix.py", line 271, in update
items0, items1 = zip(*dic.keys())
AttributeError: 'exceptions.IndexError' object has no attribute 'keys'
None
```

**Comment by rossant** [comment]
what are the actions required to reproduce the error?

**Comment by nippoo** [comment]
not sure: cf https://groups.google.com/forum/#!topic/klustaviewas/DSO6W0vU6jY (for this and #60 )
